#!/bin/bash

echo "🔧 Setting up Vercel Environment Variables..."
echo ""
echo "Run these commands in your terminal (replace with your actual values):"
echo ""
echo "# Set Google OAuth Client ID"
echo "vercel env add VITE_GOOGLE_CLIENT_ID"
echo "# When prompted, enter your Google OAuth Client ID"
echo ""
echo "# Set Backend API URL"
echo "vercel env add VITE_API_URL"
echo "# When prompted, enter: https://your-render-backend-url.onrender.com"
echo ""
echo "# Deploy with new environment variables"
echo "vercel --prod"
echo ""
echo "📝 Don't forget to:"
echo "1. Get your Google OAuth Client ID from Google Cloud Console"
echo "2. Replace 'your-render-backend-url' with your actual Render URL"
echo "3. Add your Vercel domain to Google Cloud Console OAuth settings"